# Generated by Django 4.0.1 on 2022-01-14 17:21

from django.db import migrations, models
import users.validator


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='uploaded_files', validators=[users.validator.validate_file_extension]),
        ),
    ]
